config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "users/products#index"
  resources :users, only:[:edit, :update]

  namespace :users do
    resources :carts, only: [:index, :create, :destroy] do
      post 'purchase', on: :collection
    end
    resources :products, only: [:index, :show] do
      resources :reviews, only: [:new, :create]
    end
  end

  namespace :admin do
    resources :products, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :carts
  has_many :users, through: :carts
  validates :name, :category, :image, :price, :product_code, :count, :description, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :carts
  has_many :products, through: :carts
  enum admin: { user: 0, admin: 1 }
  validates :email, :name, :kana_name, :postal_code, :address1, :address2, presence: true, uniqueness: true
  # VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
  # validates :phone, presence: true, format: { with: VALID_PHONE_REGEX }
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  before_action :require_admin!

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_path
    else
      flash.now[:alert] = "入力してください"
      render :new
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :category, :image, :price, :product_code, :count, :description)
  end

  def require_admin!
    if current_user.nil? || !current_user.admin?
      redirect_to root_path, notice: 'ページがありません'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery except: :create
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :kana_name, :postal_code, :address1, :address2, :phone])
  end
end

app/controllers/users/carts_controller.rb
class Users::CartsController < ApplicationController

  before_action :set_product_price, only: [:index, :purchase]

  def index
    @products = current_user.products.page(params[:page]).per(6)
  end

  def create
    cart = Cart.new(product_id: params[:product_id], user_id: current_user.id)
    if cart.save
      redirect_to users_carts_path
    end
  end

  def destroy
    carts = Cart.where(product_id: params[:id], user_id: current_user.id)
    cart = carts[0]
    if cart.destroy
      redirect_to users_carts_path
    end
  end


  def purchase
    Payjp.api_key = PAYJP_SECRET_KEY
    Payjp::Charge.create(currency: 'jpy', amount: @price, card: params['payjp-token'])
    carts = Cart.where(user_id: current_user.id)
    carts.each do |cart|
      cart.destroy
    end
    SampleMailer.send_when_update(current_user).deliver
    redirect_to root_path, notice: "支払いが完了しました"
  end

  private
  def set_product_price
    @products = current_user.products
    @price = 0
    @products.each do |product|
      @price += product[:price]
    end
  end
end

app/controllers/users/products_controller.rb
class Users::ProductsController < ApplicationController
  def index
    @new_products = Product.where(created_at: Time.mktime(2017, 10, 18).all_day).limit(6)
    @classic_products = Product.where(created_at: Time.mktime(2017, 10, 17).all_day).page(params[:page]).per(6)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      SampleMailer.send_when_update(current_user).deliver
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/orders/index.html.haml
= render partial: "products/nav-bar"
.order-detail__contents
  .order-detail__main_contents-wrapper
    - if @quantity.nil? || @quantity.zero?
      .order-detail__main_contents-empty カートに入っている商品はありません
    - else
      - @products.each do |product|
        .order-detail__main_contents
          .order-detail__main_contents_image
            = link_to image_tag(product.image), detail_product_path(product)
          .order-detail__main_contents__description
            .order-detail__product-name #{product.name}
            .order-detail__product_category #{product.product_category}
            .order-detail__product_code #{product.product_code}
            .order-detail__prduct_price ¥ #{product.price}
            .order-detail__attention 返品・交換対象外商品
  .order-detail__purchase_contents
    .order-detail__purchase_contents__summary
      .order-detail__summary
        %table
          %tr
            %td.title 商品合計
            %td.price ¥ #{@price}
          %tr
            %td.title 送料
            %td.price ¥ 0
          %tr
            %td.title 手数料
            %td.price ¥ 0
        %hr.summary
        %table
          %tr
            %td.title 合計金額
            %td.price_summary ¥ #{@price}
    .order-detail__purchase_contents__description
      = link_to root_path do
        = submit_tag "買い物を続ける", class: "purchase_button"
      = form_tag admin_orders_path(current_user), method: "post" do
        = submit_tag "商品を購入する", class: "purchase_button", id: "modal-open"
  .clearfix
.footer


- if @quantity.nil? || @quantity.zero?
  #modal-content
    %p 商品をカートに入れてからでなおしてくるんだな
    = link_to "Topへ戻る", root_path, id: "modal-close", class: "button-link"
- else
  #modal-content
    %p ご注文ありがとうございました！
    = link_to "Topへ戻る", root_path, id: "modal-close", class: "button-link"

app/views/admin/orders/show.html.haml
= render partial: "products/nav-bar"
.order-detail__contents
  .order-detail__main_contents-wrapper
    - if @quantity.nil? || @quantity.zero?
      .order-detail__main_contents-empty カートに入っている商品はありません
    - else
      - @products.each do |product|
        .order-detail__main_contents
          .order-detail__main_contents_image
            = link_to image_tag(product.image), detail_product_path(product)
          .order-detail__main_contents__description
            .order-detail__product-name #{product.name}
            .order-detail__product_category #{product.product_category}
            .order-detail__product_code #{product.product_code}
            .order-detail__prduct_price ¥ #{product.price}
            .order-detail__attention 返品・交換対象外商品
  .order-detail__purchase_contents
    .order-detail__purchase_contents__summary
      .order-detail__summary
        %table
          %tr
            %td.title 商品合計
            %td.price ¥ #{@price}
          %tr
            %td.title 送料
            %td.price ¥ 0
          %tr
            %td.title 手数料
            %td.price ¥ 0
        %hr.summary
        %table
          %tr
            %td.title 合計金額
            %td.price_summary ¥ #{@price}
    .order-detail__purchase_contents__description
      = link_to root_path do
        = submit_tag "買い物を続ける", class: "purchase_button"
      = form_tag admin_orders_path(current_user), method: "post" do
        = submit_tag "商品を購入する", class: "purchase_button", id: "modal-open"
  .clearfix
.footer


- if @quantity.nil? || @quantity.zero?
  #modal-content
    %p 商品をカートに入れてからでなおしてくるんだな
    = link_to "Topへ戻る", root_path, id: "modal-close", class: "button-link"
- else
  #modal-content
    %p ご注文ありがとうございました！
    = link_to "Topへ戻る", root_path, id: "modal-close", class: "button-link"

app/views/admin/products/_detail.html.haml
.description__contents__delivery-alert
  %p
    この商品は、
    %strong 最短明日の午前中
    までに届けるつもりでいます！
.description__contents__product-name
  商品名:
  = @product.name
.description__contents__product-detail
  %p 商品説明
  = @product.description
  %p 商品No：#{ @product.product_code }
  %p カテゴリー：#{ @product.category }
  %p 原産国：
  %p 残り在庫数：#{ @product.count }
.description__contents__parchace-button
  .tmp-price #{ @product.price }円 税込
  / = form_tag add_to_cart_user_order_path(current_user), method: "get" do
  /   = submit_tag "カートに入れる", class: "add_cart_button"

app/views/admin/products/_nav-bar.html.haml
- if user_signed_in?
  - unless session[:quantity] == nil || session[:quantity] == 0
    .current-cart-quantity
      %p #{session[:quantity]}
.nav__bar
  .site-title
    = link_to 'ZOZOTOWN', root_path, class: "site-title"
  - if user_signed_in?
    .logout
      = link_to destroy_user_session_path, method: :delete do
        %i.fa.fa-sign-out
    .user-edit
      = link_to edit_user_registration_path(current_user) do
        %i.fa.fa-pencil-square-o
    .user-cart
      / = link_to carts_path do
      /   %i.fa.fa-shopping-cart
    - if true #(current_user.authority == 1 )
      .product-edit
        = link_to new_admin_product_path() do
          %i.fa.fa-shopping-bag
      .admin-user-edit
        = link_to edit_user_registration_path(current_user) do
          %i.fa.fa-user-circle
  - else
    .new-user
      = link_to new_user_registration_path do
        %i.fa.fa-user-plus
    .login
      = link_to new_user_session_path do
        %i.fa.fa-sign-in

app/views/admin/products/index.html.haml
!!!
%body
  = render partial: "nav-bar"
  .contents
    .main_contents
      .left__contents
        = render partial: "category-list"
      .center__contents
        .center__contents_wrapper
          .center__contents_campain
            %h5.center__contents_campain-title キャンペーン
            %hr.center__contents_campain-line
              .center__contents_campain__top
              - @products.each do |product|
                .center__contents_campain__top-product
                  = link_to image_tag(product.image), admin_product_path(product)
                  %p.center__contents_campain_product-title
                    = product.name
                  %p.center__contents_campain_product-price
                    #{ product.price } 円 税込
            / .center__contents_campain
          /   %h5.center__contents_campain-title　コーディネート
          /   %hr.center__contents_campain-line
          /   .center__contents_campain__top
          /     - @products.each do |product|
          /       .center__contents_campain__top-product
          /         = link_to image_tag(product.image), admin_product_path(product)
          /         %p.center__contents_campain_product-title
          /           = product.name
          /         %p.center__contents_campain_product-price
          / .center__contents_campain
          /   %h5.center__contents_campain-title コーディネート
          /   %hr.center__contents_campain-line
          /   .center__contents_campain__top
          /     .center__contents_campain__top-product
      .right__contents
        .right__contents_shop-news-title ショップニュース
        .right__contents_shop-news-list
          = image_tag 'shipping_cost.jpeg', class: "right-contents-shop-pop"
          .right__contents_shop-news-detail
            %p.shop-news-detail_title
            %p.shop-news-detail_description 送料自由
        = render partial: "shop-list"
  .footer

app/views/admin/products/new.html.haml
= render partial: "users/products/nav-bar"
.admin-page
  .admin-page__outer
    .admin-page__prouct-title 商品登録
    .admin-page__inner--wrapper
      .product-select_field
      .product-new_field
        = form_for( @product, :url => {:controller => "admin/products", :action => :create }) do |f|
          .product-new_field-top
            .product-new_field-top__image
              .product-new_field__show-image
                %output#js-show-image-field
              .product-new_field__show-image-button#js-show-image 商品画像を選択する
              = f.file_field :image, id: "file", style: "display:none", value: ""
            .product-new_field-top__detail
              .product-new_field__name
                .product-new_field__label
                  = f.label :name, value: "商品名"
                = f.text_area :name, class: "input_product_name", value: ""
              .product-new_field__product-category
                .product-new_field__label
                  = f.label :category, value: "商品カテゴリ"
                = f.select :category, [["トップス"], ["ジャケット/アウター"], ["パンツ"], ["オールインワン"], ["スカート"], ["ワンピース"], ["スーツ/ネクタイ"], ["バッグ"], ["シューズ"], ["ファッション雑貨"], ["財布/小物"], ["ヘアアクセサリー"], ["アクセサリー"], ["アンダーウェア"], ["レッグウェア"], ["帽子"], ["インテリア"], ["食器/キッチン"], ["雑貨/ホビー/スポーツ"], ["コスメ/香水"], ["音楽/本・雑誌"], ["水着/着物・浴衣"], ["マタニティ/ベビー"], ["その他"]], {include_blank: true}, {class: "input_product_category"}
              .product-new_field__product-code
                .product-new_field__label
                  = f.label :product_code, value: "品番"
                = f.text_area :product_code, class: "input_product_code", value: ""
              .product-new_field__price
                .product-new_field__label
                  = f.label :price, value: "価格（税抜）"
                = f.text_area :price, class: "input_product_price", value: ""
              .product-new_field__count
                .product-new_field__label
                  = f.label :count, value: "在庫数"
                = f.text_area :count, class: "input_product_count", value: ""
          .product-new_field-bottom
            = f.label :description, value: "商品説明"
            = f.text_area :description, class: "input_product_description", value: ""
            = f.submit "保 存", class: 'product-new-btn'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ZOZOTOWN
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

    %p.notice
      = notice
    %p.alert
      = alert

    = yield

app/views/users/carts/index.html.haml
= render partial: "users/products/nav-bar"
.order-detail__contents
  .order-detail__main_contents-wrapper
    / - if @quantity.nil? || @quantity.zero?
    /   .order-detail__main_contents-empty カートに入っている商品はありません
    / - else
    - @products.each do |product|
      .order-detail__main_contents
        .order-detail__main_contents_image
          = link_to image_tag(product.image), users_cart_path(product), method: "delete"
        .order-detail__main_contents__description
          .order-detail__product-name #{product.name}
          .order-detail__product_category #{product.category}
          .order-detail__product_code #{product.product_code}
          .order-detail__prduct_price #{ number_to_currency(product.price) }
          .order-detail__attention 返品・交換対象外商品
    = paginate(@products)
  .order-detail__purchase_contents
    .order-detail__purchase_contents__summary
      .order-detail__summary
        %table
          %tr
            %td.title 商品合計
            %td.price  #{ number_to_currency(@price) }
          %tr
            %td.title 送料
            %td.price 0円
          %tr
            %td.title 手数料
            %td.price 0円
        %hr.summary
        %table
          %tr
            %td.title 合計金額
            %td.price_summary #{ number_to_currency(@price) }
    .order-detail__purchase_contents__description
      = link_to root_path do
        = submit_tag "買い物を続ける", class: "purchase_button"
      = form_tag action: "purchase", method: "post" do
        %script.payjp-button{"data-key": "#{PAYJP_PUBLIC_KEY}", src: "https://checkout.pay.jp", type: "text/javascript"}
  .clearfix
.footer

/ - if @quantity.nil? || @quantity.zero?
/   #modal-content
/     %p 商品をカートに入れてからでなおしてくるんだな
/     = link_to "Topへ戻る", root_path, id: "modal-close", class: "button-link"
/ - else
/   #modal-content
/     %p ご注文ありがとうございました！
/     = link_to "Topへ戻る", root_path, id: "modal-close", class: "button-link"

app/views/users/products/_category-list.html.haml
.left__contents_search-method
  .left__contents_product-search-method_field
  .left__contents_product-search-method_title 探す
  .left__contents_product-search-method_list ブランドから探す
  .left__contents_product-search-method_list ショップから探す
  .left__contents_product-search-method_list ランキングから探す
  .left__contents_product-search-method_list コーディネートから探す
  .left__contents_product-search-method_list こだわり条件から探す
.left__contents_product-category-list
  .left__contents_product-category-list_title カテゴリ
  .left__contents_product-category-list_product-name トップス
  .left__contents_product-category-list_product-name ジャケット/アウター
  .left__contents_product-category-list_product-name パンツ
  .left__contents_product-category-list_product-name オールインワン
  .left__contents_product-category-list_product-name スカート
  .left__contents_product-category-list_product-name ワンピース
  .left__contents_product-category-list_product-name スーツ/ネクタイ
  .left__contents_product-category-list_product-name バッグ
  .left__contents_product-category-list_product-name シューズ
  .left__contents_product-category-list_product-name ファッション雑貨
  .left__contents_product-category-list_product-name 財布/小物
  .left__contents_product-category-list_product-name ヘアアクセサリー
  .left__contents_product-category-list_product-name アクセサリー
  .left__contents_product-category-list_product-name アンダーウェア
  .left__contents_product-category-list_product-name レッグウェア
  .left__contents_product-category-list_product-name 帽子
  .left__contents_product-category-list_product-name インテリア
  .left__contents_product-category-list_product-name 食器/キッチン
  .left__contents_product-category-list_product-name 雑貨/ホビー/スポーツ
  .left__contents_product-category-list_product-name コスメ/香水
  .left__contents_product-category-list_product-name 音楽/本・雑誌
  .left__contents_product-category-list_product-name 水着/着物・浴衣
  .left__contents_product-category-list_product-name マタニティ/ベビー
  .left__contents_product-category-list_product-name その他

app/views/users/products/_detail.html.haml
.description__contents__delivery-alert
  %p
    この商品は、
    %strong 最短明日の午前中
    までに届けるつもりでいます！
.description__contents__product-name
  商品名:
  = @product.name
.description__contents__product-detail
  %p 商品説明
  = @product.description
  %p 商品No：#{ @product.product_code }
  %p カテゴリー：#{ @product.category }
  %p 原産国：
  %p 残り在庫数：#{ @product.count }
.description__contents__purchace-button
  .tmp-price #{ number_to_currency(@product.price) } 税込
  = form_tag users_carts_path, method: "post" do
    = hidden_field_tag :product_id, @product.id
    = submit_tag("カートに入れる", name: nil, class: "add_cart_button")

app/views/users/products/_nav-bar.html.haml
- if user_signed_in?
  - unless session[:quantity] == nil || session[:quantity] == 0
    .current-cart-quantity
      %p #{session[:quantity]}
.nav__bar
  .site-title
    = link_to 'ZOZOTOWN', root_path, class: "site-title"
  - if user_signed_in?
    .logout
      = link_to destroy_user_session_path, method: :delete do
        %i.fa.fa-sign-out
    .user-edit
      = link_to edit_user_registration_path(current_user) do
        %i.fa.fa-pencil-square-o
    .user-cart
      = link_to users_carts_path do
        %i.fa.fa-shopping-cart
    - if true #(current_user.authority == 1 )
      .product-edit
        = link_to new_admin_product_path() do
          %i.fa.fa-shopping-bag
      .admin-user-edit
        = link_to edit_user_registration_path(current_user) do
          %i.fa.fa-user-circle
  - else
    .new-user
      = link_to new_user_registration_path do
        %i.fa.fa-user-plus
    .login
      = link_to new_user_session_path do
        %i.fa.fa-sign-in
.subbar
  %p.all
    すべて
  %p.men
    メンズ
  %p.women
    レディース
  %p.kids
    キッズ

app/views/users/products/_shop-list.html.haml
.right__contents_shop-news-list
  = image_tag 'img35.jpg', class: "right-contents-shop-pop"
.right__contents_shop-news-list
  = image_tag 'img36.jpg', class: "right-contents-shop-pop"
.right__contents_shop-news-list
  = image_tag 'img15.jpg', class: "right-contents-shop-pop"
.right__contents_shop-news-list
  / = image_tag 'img21.jpeg', class: "right-contents-shop-pop"
/ .right__contents_shop-news-list
/   = image_tag 'agnes_b_ladys.jpeg', class: "right-contents-shop-pop"
/ .right__contents_shop-news-list
/   = image_tag 'agnes_b_ladys.jpeg', class: "right-contents-shop-pop"
/ .right__contents_shop-news-list
/   = image_tag 'agnes_b_ladys.jpeg', class: "right-contents-shop-pop"
/ .right__contents_shop-news-list
/   = image_tag 'agnes_b_ladys.jpeg', class: "right-contents-shop-pop"
/ .right__contents_shop-news-list
/   = image_tag 'agnes_b_ladys.jpeg', class: "right-contents-shop-pop"
/ .right__contents_shop-news-list
/   = image_tag 'agnes_b_ladys.jpeg', class: "right-contents-shop-pop"
/ .right__contents_shop-news-list
/   = image_tag 'agnes_b_ladys.jpeg', class: "right-contents-shop-pop"
/ .right__contents_shop-news-list
/   = image_tag 'agnes_b_ladys.jpeg', class: "right-contents-shop-pop"

app/views/users/products/index.html.haml
!!!
%body
  = render partial: "nav-bar"
  .contents
    .main_contents
      .left__contents
        = render partial: "category-list"
      .center__contents
        .center__contents_slider
          %ul#slider
            %li
              = image_tag "img31.jpg"
            %li
              = image_tag "img32.jpg"
            %li
              = image_tag "img30.jpg"
            %li
              = image_tag "img34.jpg"
            %li
              = image_tag "img35.jpg"
            %li
              = image_tag "img37.jpg"
            %li
              = image_tag "img39.jpg"
            %li
              = image_tag "img40.jpg"
            %li
              = image_tag "img41.jpg"
            %li
              = image_tag "img45.jpg"
            %li
              = image_tag "img13.jpg"
        .center__contents_wrapper
          .center__contents_campain
            %h5.center__contents_campain-title 新着アイテム
            %hr.center__contents_campain-line
              .center__contents_campain__top
              - @new_products.each do |product|
                .center__contents_campain__top-product
                  = link_to image_tag(product.image), users_product_path(product)
                  %p.center__contents_campain_product-title
                    = product.name
                  %p.center__contents_campain_product-price
                    #{ number_to_currency(product.price) }  税込
        .center__contents_wrapper
          .center__contents_campain
            %h5.center__contents_campain-title 定番アイテム
            %hr.center__contents_campain-line
            .center__contents_campain__top
              - @classic_products.each do |product|
                .center__contents_campain__top-product
                  = link_to image_tag(product.image), users_product_path(product)
                  %p.center__contents_campain_product-title
                    = product.name
                  %p.center__contents_campain_product-price
                    #{ number_to_currency(product.price) }  税込
            = paginate(@classic_products)
      .right__contents
        .right__contents_shop-news-title ショップニュース
        .right__contents_shop-news-list
          = image_tag 'img18.jpg', class: "right-contents-shop-pop"
          .right__contents_shop-news-detail
            %p.shop-news-detail_title
            %p.shop-news-detail_description
        = render partial: "shop-list"
  .footer

app/views/users/products/show.html.haml
= render partial: "nav-bar"
.product-detail__contents
  .product-detail__main_contents
    .product-detail__contents_image
      = image_tag @product.image
    .product-detail__contents__description
      .product-detail__contents__item-description
        = render partial: "detail"
.footer

/ #modal-cart-content
/   %p #{@product.name} をカートに保存しました！
/   = link_to "カートへ", user_orders_path(current_user), class: "button-link"